# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./models:/app/models  # Para armazenar modelos YOLO
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=camera_detection
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=camera_detection
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: