"""added avg roadState

Revision ID: 5616fd3f225d
Revises: 7ba50691221b
Create Date: 2025-03-09 18:17:52.613611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5616fd3f225d'
down_revision: Union[str, None] = '7ba50691221b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_state', sa.Column('moving_avg_state', sa.String(length=50), nullable=True))
    op.add_column('road_state', sa.Column('moving_avg_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_state', 'moving_avg_percentage')
    op.drop_column('road_state', 'moving_avg_state')
    # ### end Alembic commands ###
