"""added RoadStateModel remove unique constraint on road_state

Revision ID: 7ba50691221b
Revises: 8554ec42d905
Create Date: 2025-03-04 14:29:31.832153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba50691221b'
down_revision: Union[str, None] = '8554ec42d905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('road_state_road_state_key', 'road_state', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('road_state_road_state_key', 'road_state', ['road_state'])
    # ### end Alembic commands ###
