"""added RoadStateModel confidence column

Revision ID: 8554ec42d905
Revises: b134bcbe6885
Create Date: 2025-03-04 14:21:34.735383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8554ec42d905'
down_revision: Union[str, None] = 'b134bcbe6885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_state', sa.Column('confidence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_state', 'confidence')
    # ### end Alembic commands ###
