"""added state duration field

Revision ID: fc8b2c73cb98
Revises: 5616fd3f225d
Create Date: 2025-03-09 18:35:28.046403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8b2c73cb98'
down_revision: Union[str, None] = '5616fd3f225d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_state', sa.Column('state_duration', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_state', 'state_duration')
    # ### end Alembic commands ###
